#!/usr/bin/env bash

ARCH=$(uname -m)
case "${ARCH}" in
  aarch64)
    gotty-aarch64 "$@"
    ;;
  x86_64)
    gotty-x86_64 "$@"
    ;;
  *)
    echo "No gotty version found for ${ARCH}"
    exit 1
    ;;
esac
